name: Build static library dependencies for windows
on:
  workflow_dispatch:

  push:
    branches-ignore:
      - master
    paths:
      - ".github/workflows/**"
      - "Makefile"
jobs:
  build-windows-amd64:
    name: Windows (64 Bit)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'duckdb/duckdb'
          ref: 'v0.9.2'
          fetch-depth: 1
          path: 'duckdb'

      - uses: actions/setup-python@v4
        with:
          python-version: '3.7'

      - name: Setup Ccache
        uses: hendrikmuhs/ccache-action@main
        with:
          key: ${{ github.job }}
          save: ${{ github.ref == 'refs/v0.9.2' || github.repository != 'duckdb/duckdb' }}

      - name: Install pytest
        run: |
          python -m pip install pytest

      - name: Build
        shell: bash
        run: |
          cd duckdb  &&\
          mkdir -p build/release &&\
          python scripts/windows_ci.py &&\
          ls -al &&\
          cmake -B build/release -DBUILD_SHELL=0 -DBUILD_BENCHMARK=0 -DBUILD_JDBC=0 -DBUILD_ODBC=0 -DBUILD_PYTHON=0 -DCMAKE_BUILD_TYPE=Release -DCMAKE_GENERATOR_PLATFORM=x64 -DENABLE_EXTENSION_AUTOLOADING=1 -DENABLE_EXTENSION_AUTOINSTALL=1 -DDUCKDB_EXTENSION_CONFIGS="${GITHUB_WORKSPACE}/duckdb/.github/config/bundled_extensions.cmake" -DBUILD_ODBC_DRIVER=1 -DDISABLE_UNITY=1 &&\
          pwd &&\
          cmake --build build/release --config Release &&\
          ls -alRh  build/release/
      - name: Deploy
        shell: bash
        run: |
          ls -al &&\
          cd duckdb &&\
          python scripts/amalgamation.py &&\
          choco install zip -y --force &&\
          zip -j libduckdb-windows-amd64.zip src/amalgamation/duckdb.hpp src/include/duckdb.h build/release/extension/icu/icu.duckdb_extension build/release/extension/icu/Release/icu_extension.lib build/release/extension/fts/fts.duckdb_extension build/release/extension/fts/Release/fts_extension.lib build/release/extension/excel/excel.duckdb_extension build/release/extension/excel/Release/excel_extension.lib build/release/extension/visualizer/visualizer.duckdb_extension build/release/extension/visualizer/Release/visualizer_extension.lib build/release/extension/tpch/tpch.duckdb_extension build/release/extension/tpch/Release/tpch_extension.lib build/release/extension/tpcds/tpcds.duckdb_extension build/release/extension/tpcds/Release/tpcds_extension.lib build/release/extension/sqlsmith/sqlsmith.duckdb_extension build/release/extension/sqlsmith/Release/sqlsmith_extension.lib build/release/extension/json/json.duckdb_extension build/release/extension/json/Release/json_extension.lib build/release/extension/inet/inet.duckdb_extension build/release/extension/inet/Release/inet_extension.lib build/release/extension/parquet/parquet.duckdb_extension build/release/extension/parquet/Release/parquet_extension.lib build/release/src/Release/duckdb_static.lib build/release/src/Release/duckdb.dll build/release/src/Release/duckdb.exp build/release/src/Release/duckdb.lib build/release/third_party/fsst/Release/duckdb_fsst.lib build/release/third_party/hyperloglog/Release/duckdb_hyperloglog.lib build/release/third_party/mbedtls/Release/duckdb_mbedtls.lib build/release/third_party/miniz/Release/duckdb_miniz.lib build/release/third_party/re2/Release/duckdb_re2.lib build/release/third_party/utf8proc/Release/duckdb_utf8proc.lib build/release/third_party/libpg_query/Release/duckdb_pg_query.lib build/release/third_party/fastpforlib/Release/duckdb_fastpforlib.lib build/release/third_party/fmt/Release/duckdb_fmt.lib
      - uses: actions/upload-artifact@v3
        with:
          name: duckdb-binaries-windows
          path: |
            duckdb/libduckdb-windows-amd64.zip